CROSS_COMPILE 	?= arm-linux-gnueabihf-
TARGET		 	?= int

CC				:= $(CROSS_COMPILE)gcc
LD 				:= $(CROSS_COMPILE)ld
OBJCOPY 		:= $(CROSS_COMPILE)objcopy
OBJDUMP 		:= $(CROSS_COMPILE)objdump

INCUDIRS		:= 	imx6u	\
					bsp/clk	\
					bsp/led \
					bsp/delay \
					bsp/beep \
					bsp/key	\
					bsp/gpio \
					bsp/int

SRCDIRS			:= 	project	\
					bsp/clk	\
					bsp/led	\
					bsp/delay \
					bsp/beep \
					bsp/key	\
					bsp/gpio \
					bsp/int

INCLUDE			:=	$(patsubst %, -I %, $(INCUDIRS))

SFILES			:=	$(foreach dir, $(SRCDIRS), $(wildcard $(dir)/*.s))
CFILES			:=	$(foreach dir, $(SRCDIRS), $(wildcard $(dir)/*.c))

SFILENDIR		:= $(notdir $(SFILES))
CFILENDIR		:= $(notdir $(CFILES))

SOBJS			:=	$(patsubst %, obj/%, $(SFILENDIR:.s=.o))
COBJS			:= 	$(patsubst %, obj/%, $(CFILENDIR:.c=.o))

OBJS 			:= 	$(SOBJS) $(COBJS)

VPATH			:= 	$(SRCDIRS)

.PHONY:clean


$(TARGET).bin : $(OBJS)
	$(LD) -Timx6u.lds -o $(TARGET).elf $^
	$(OBJCOPY) -O binary -S $(TARGET).elf $@
	$(OBJDUMP) -D -m arm $(TARGET).elf > $(TARGET).dis

$(SOBJS) : obj/%.o :%.s 	
	$(CC) -Wall -nostdlib -c -O2 $(INCLUDE) -o $@ $<

$(COBJS) : obj/%.o :%.c 	
	$(CC) -Wall -nostdlib -c -O2 $(INCLUDE) -o $@ $<

clean:
	rm -rf *.elf *.bin *.dis $(OBJS)
